import type { Guide } from "@/content/types";

export const earlySkillRotationGuide: Guide = {
  "slug": "early-skill-rotation",
  "title": "초반에 유용한 영웅 스킬 로테이션",
  "category": "beginner",
  "status": "coming",
  "description": "초반에 사용하는 주요 영웅들의 스킬 로테이션을 정리하는 공략.",
  "html": "<div class=\"callout info\"><div class=\"callout-icon\">i</div><div class=\"callout-body\"><p>초반에 사용하시는 분들을 위해 넉넉하게 여유를 가지고 찍은 영상입니다.</p><p>충분히 따라하실 수 있습니다.</p></div></div><section class=\"article-subsection depth-2\" id=\"토르\"><h3>토르</h3><figure class=\"media-asset video\"><video controls=\"\" preload=\"metadata\"><source src=\"/media/video1.mp4\" type=\"video/mp4\"/></video></figure><p>5번 스킬 망치 띄우면 &gt; 4번 스킬 왔다갔다 끝나면 &gt; 3번 스킬 돌진 후 내려치기 끝나면 &gt; 2번 빔 쏘면</p><p>1번 스킬, 이후 5번 4번 쿨타임 차면 동일하게 5번 4번 사용 후 3번 누르고 6번 스킬 끝까지 보기</p></section><section class=\"article-subsection depth-2\" id=\"아이언-맨\"><h3>아이언 맨</h3><figure class=\"media-asset video\"><video controls=\"\" preload=\"metadata\"><source src=\"/media/video3.mp4\" type=\"video/mp4\"/></video></figure><p>3 즉캔 → 4 미사일 발사 → 5 끝까지 보고 → 2 → 1</p><p>3티기가 있을 경우 3 → 4 미사일캔 → 5 즉캔 → 6 끝까지 보기 → 2 → 1</p></section><section class=\"article-subsection depth-2\" id=\"루나-스노우\"><h3>루나 스노우</h3><figure class=\"media-asset video\"><video controls=\"\" preload=\"metadata\"><source src=\"/media/video1 1.mp4\" type=\"video/mp4\"/></video></figure><p>공속이 느린 경우 느긋하게 눌러주세요</p><p>5캔 4캔 3캔 1캔 2스케이트 다 타고 1 쓰시면 됩니다<br/>3티 4티는 충전되면 바로 쓰시고 3티는 즉캔 가능합니다</p></section><section class=\"article-subsection depth-2\" id=\"스톰\"><h3>스톰</h3><figure class=\"media-asset video\"><video controls=\"\" preload=\"metadata\"><source src=\"/media/video18.mp4\" type=\"video/mp4\"/></video></figure><p>3 날아오르면 → 5 즉캔 → 4 날아오르면 → 2 회오리가 보이면 → 1 돌진</p><p>3티 충전 시 : 3 5 4 2 6 만세 자세로 날아오르고 앞으로 팔을 뻗으면 2 1</p></section><section class=\"article-subsection depth-2\" id=\"고스트-라이더\"><h3>고스트 라이더</h3></section><section class=\"article-subsection depth-2\" id=\"section-da39a3ee\"><h3></h3></section>",
  "searchText": "초반에 유용한 영웅 스킬 로테이션 초반에 사용하는 주요 영웅들의 스킬 로테이션을 정리하는 공략.  i 초반에 사용하시는 분들을 위해 넉넉하게 여유를 가지고 찍은 영상입니다. 충분히 따라하실 수 있습니다. 토르 (사진) 5번 스킬 망치 띄우면 > 4번 스킬 왔다갔다 끝나면 > 3번 스킬 돌진 후 내려치기 끝나면 > 2번 빔 쏘면 1번 스킬, 이후 5번 4번 쿨타임 차면 동일하게 5번 4번 사용 후 3번 누르고 6번 스킬 끝까지 보기 아이언 맨 (사진) 3 즉캔 → 4 미사일 발사 → 5 끝까지 보고 → 2 → 1 3티기가 있을 경우 3 → 4 미사일캔 → 5 즉캔 → 6 끝까지 보기 → 2 → 1 루나 스노우 (사진) 공속이 느린 경우 느긋하게 눌러주세요 5캔 4캔 3캔 1캔 2스케이트 다 타고 1 쓰시면 됩니다 3티 4티는 충전되면 바로 쓰시고 3티는 즉캔 가능합니다 스톰 (사진) 3 날아오르면 → 5 즉캔 → 4 날아오르면 → 2 회오리가 보이면 → 1 돌진 3티 충전 시 : 3 5 4 2 6 만세 자세로 날아오르고 앞으로 팔을 뻗으면 2 1 고스트 라이더",
  "aliases": [],
  "text": "i 초반에 사용하시는 분들을 위해 넉넉하게 여유를 가지고 찍은 영상입니다. 충분히 따라하실 수 있습니다. 토르 5번 스킬 망치 띄우면 > 4번 스킬 왔다갔다 끝나면 > 3번 스킬 돌진 후 내려치기 끝나면 > 2번 빔 쏘면 1번 스킬, 이후 5번 4번 쿨타임 차면 동일하게 5번 4번 사용 후 3번 누르고 6번 스킬 끝까지 보기 아이언 맨 3 즉캔 → 4 미사일 발사 → 5 끝까지 보고 → 2 → 1 3티기가 있을 경우 3 → 4 미사일캔 → 5 즉캔 → 6 끝까지 보기 → 2 → 1 루나 스노우 공속이 느린 경우 느긋하게 눌러주세요 5캔 4캔 3캔 1캔 2스케이트 다 타고 1 쓰시면 됩니다 3티 4티는 충전되면 바로 쓰시고 3티는 즉캔 가능합니다 스톰 3 날아오르면 → 5 즉캔 → 4 날아오르면 → 2 회오리가 보이면 → 1 돌진 3티 충전 시 : 3 5 4 2 6 만세 자세로 날아오르고 앞으로 팔을 뻗으면 2 1 고스트 라이더"
};
